
default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: painless_rails_development

test:
  <<: *default
  database: painless_rails_test

production:
  <<: *default
  database: painless_rails_production
  username: painless_rails
  password: <%= ENV['PAINLESS_RAILS_DATABASE_PASSWORD'] %>
